lib/data/provider/server.dart

fix: can not get chinese mem

---

.dart_tool/flutter_gen/gen_l10n/l10n.dart
.dart_tool/flutter_gen/gen_l10n/l10n_en.dart
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
lib/app.dart
lib/core/utils/ui.dart
lib/l10n/app_en.arb
lib/view/page/home.dart
lib/view/page/server/tab.dart
lib/view/page/setting.dart
pubspec.lock
pubspec.yaml

Hey there,
I have found this project and really liked the features, but wasn't sure about the design (as it looked outdated). After a few days of using the app I made my own small tweaks and changes to it. Using Material 3 and a proper color scheme by using the ColorSchemeSeed, the app looked quite good. So i decided to open this pull request.
Here is a link to a few images of the new design: https://imgur.com/a/2U3bKGo
I also changed the navigation bar at the bottom to make it look more like Material 3.
Have a great day 👋

Material 3

---

.dart_tool/flutter_gen/gen_l10n/l10n_de.dart
lib/l10n/app_de.arb
lib/view/page/setting.dart
lib/view/page/snippet/edit.dart

- making the ListTile in the settings clickable (making it more reachable and easier to open the menu)
- fixed a typo in german
- make snippets multiline (can easily enter a new line with the keyboard)
Have a great one 👋

UI Improvements

---

lib/view/page/server/tab.dart

#88 #74 fix: rootDisk if not found

---

android/app/build.gradle

https://github.com/lollipopkit/flutter_server_box/issues/381#issuecomment-2163425536

Add abiCodes

---

lib/app.dart
lib/view/page/home/home.dart
lib/view/page/home/wear.dart
lib/view/page/private_key/list.dart
lib/view/page/server/tab.dart
lib/view/page/snippet/edit.dart
lib/view/page/ssh/page.dart
lib/view/page/storage/sftp.dart
pubspec.lock
pubspec.yaml

Android - default to English

---

lib/core/utils/window_size_listener.dart
lib/data/store/setting.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/l10n/app_fr.arb
lib/l10n/app_id.arb
lib/l10n/app_ja.arb
lib/l10n/app_nl.arb
lib/l10n/app_pt.arb
lib/l10n/app_ru.arb
lib/l10n/app_zh.arb
lib/l10n/app_zh_tw.arb
lib/main.dart
lib/view/page/setting/entry.dart
lib/view/page/setting/platform/platform_pub.dart
pubspec.lock
pubspec.yaml

feat: remember window size

---

lib/main.dart
pubspec.lock
pubspec.yaml

fix: `hideTitleBar` doesn't work

---

lib/view/page/setting/entry.dart

fix: batch delete servers

---

lib/data/res/github_id.dart

chore: add participants

---

lib/data/model/container/image.dart
lib/data/provider/container.dart

fix: docker parse

---

lib/intro.dart
pubspec.lock
pubspec.yaml

fix: always enter intro page

---

pubspec.lock
pubspec.yaml

fix: linux build

---

pubspec.lock
pubspec.yaml

自动执行代码段无法取消选择

---

lib/view/page/ssh/tab.dart

fix: ssh card tap area

---

lib/main.dart
windows/runner/win32_window.cpp

拉取这个之前先拉取 https://github.com/lppcg/fl_lib/pull/3 ，否则在非 release 构建，窗口会显示不出

fix: window blink on startup

---

lib/view/page/home/appbar.dart

fix https://github.com/lollipopkit/flutter_server_box/issues/396

fix: desktop window appbar

---

.vscode/launch.json
README.md
README_zh.md
lib/data/provider/app.dart
lib/view/page/setting/entry.dart

fix: version display

---

.metadata
lib/data/model/app/backup.dart
lib/data/res/build_data.dart
lib/intro.dart
lib/main.dart
lib/view/page/setting/entry.dart
lib/view/page/ssh/tab.dart
linux/CMakeLists.txt
linux/flutter/CMakeLists.txt
linux/my_application.cc
pubspec.lock
pubspec.yaml

fix: linux duplicated title bar

---

lib/core/extension/sftpfile.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/l10n/app_fr.arb
lib/l10n/app_id.arb
lib/l10n/app_ja.arb
lib/l10n/app_nl.arb
lib/l10n/app_pt.arb
lib/l10n/app_ru.arb
lib/l10n/app_zh.arb
lib/l10n/app_zh_tw.arb
lib/view/page/storage/sftp.dart
lib/view/widget/unix_perm.dart

feat: sftp perm setting & path copy

---

lib/data/model/app/shell_func.dart
lib/data/provider/server.dart
lib/main.dart
lib/view/page/process.dart
lib/view/page/server/tab.dart
pubspec.lock
pubspec.yaml

fix: termux compatibility

---

lib/data/model/app/shell_func.dart
lib/data/model/server/cpu.dart
lib/data/model/server/server_status_update_req.dart
lib/view/page/server/detail/view.dart

feat: display cpu model

---

lib/core/route.dart
lib/data/model/server/snippet.dart
lib/view/page/setting/platform/ios.dart
lib/view/page/snippet/edit.dart
pubspec.lock
pubspec.yaml

feat: import snippets from file/network/clipboard

---

lib/data/model/server/server_private_info.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/l10n/app_fr.arb
lib/l10n/app_id.arb
lib/l10n/app_ja.arb
lib/l10n/app_nl.arb
lib/l10n/app_pt.arb
lib/l10n/app_ru.arb
lib/l10n/app_tr.arb
lib/l10n/app_zh.arb
lib/l10n/app_zh_tw.arb
lib/view/page/backup.dart
lib/view/page/snippet/edit.dart
lib/view/page/snippet/list.dart

opt.: bulk import servers

---

lib/core/route.dart
lib/view/page/home/appbar.dart
lib/view/page/home/home.dart
lib/view/page/ssh/page.dart
lib/view/page/ssh/tab.dart
macos/Podfile.lock
macos/Runner/AppDelegate.swift
pubspec.lock

fix: ssh tab focus mgmt

---

lib/data/model/server/server_private_info.dart
lib/view/page/server/detail/view.dart

opt.: hide logo if distribution == null

---

lib/app.dart
lib/intro.dart

fix: lang switch

---

lib/view/page/server/tab.dart
lib/view/page/ssh/tab.dart
macos/Podfile.lock

fix: ssh tab page UI

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/tech/lolli/toolbox/ForegroundService.kt
android/app/src/main/kotlin/tech/lolli/toolbox/MainActivity.kt
lib/main.dart
lib/view/page/ssh/tab.dart

new: custom foreground service on Android

---

lib/data/model/app/backup.dart

fix: backup on windows

---

lib/data/model/app/backup.dart
lib/data/model/app/backup.g.dart
lib/data/model/app/tag_pickable.dart
lib/data/model/server/server.dart
lib/data/model/server/snippet.dart
lib/data/store/no_backup.dart
lib/data/store/setting.dart
lib/main.dart

fix: snippet fmt

---

lib/core/sync.dart
lib/data/provider/private_key.dart
lib/data/provider/server.dart
lib/data/provider/snippet.dart
lib/data/res/store.dart
lib/data/store/container.dart
lib/data/store/history.dart
lib/data/store/private_key.dart
lib/data/store/server.dart
lib/data/store/setting.dart
lib/data/store/snippet.dart
lib/main.dart
lib/view/page/backup.dart
lib/view/page/home/appbar.dart
lib/view/page/ssh/page.dart
pubspec.lock
pubspec.yaml

opt.: sync immediately after changes

---

lib/core/route.dart
lib/data/model/app/tab.dart
lib/data/model/server/server_private_info.dart
lib/data/provider/server.dart
lib/view/page/backup.dart
lib/view/page/home/appbar.dart
lib/view/page/home/home.dart
lib/view/page/private_key/list.dart
lib/view/page/server/detail/view.dart
lib/view/page/server/edit.dart
lib/view/page/server/tab.dart
lib/view/page/server/top_bar.dart
lib/view/page/setting/entry.dart
lib/view/page/snippet/list.dart
lib/view/page/ssh/page.dart
lib/view/page/storage/local.dart
lib/view/page/storage/sftp.dart
lib/view/page/storage/sftp_mission.dart
lib/view/widget/server_func_btns.dart
pubspec.lock
pubspec.yaml

opt.: redesigned settings page

---

android/app/src/main/kotlin/tech/lolli/toolbox/ForegroundService.kt
android/app/src/main/kotlin/tech/lolli/toolbox/MainActivity.kt
lib/core/channel/bg_run.dart
lib/main.dart
lib/view/page/ssh/page.dart

opt.: dismiss notification if no ssh conn

---

lib/data/model/ssh/virtual_key.dart
lib/data/model/ssh/virtual_key.g.dart
lib/data/store/setting.dart
lib/view/page/ssh/page.dart

opt.: more virtual keys

---

lib/view/page/storage/local.dart

修复路径在windos下读取不到的问题

---

lib/view/page/server/detail/view.dart
lib/view/page/server/tab.dart
pubspec.lock
pubspec.yaml

bug: can't share server via qr_code

---

lib/view/page/server/top_bar.dart

opt.: display settings btn in fullscreen mode

---

lib/view/widget/unix_perm.dart

fix: unix perm switcher

---

macos/Runner/DebugProfile.entitlements
macos/Runner/Release.entitlements

bug: can't select file on macOS

---

lib/view/page/home.dart
lib/view/page/setting/entries/app.dart
lib/view/page/setting/entry.dart
lib/view/page/setting/platform/android.dart
lib/view/page/setting/platform/ios.dart
lib/view/page/setting/platform/platform_pub.dart
pubspec.lock
pubspec.yaml

new: `bio_auth` -> `local_auth`

---

lib/data/model/server/server_status_update_req.dart
lib/data/provider/server.dart
lib/main.dart
test/system_dist_test.dart

fix: hostname parsing
